// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: factorio_blueprints/v1/item.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Item_Item int32

const (
	Item_ITEM_UNSPECIFIED Item_Item = 0
)

// Enum value maps for Item_Item.
var (
	Item_Item_name = map[int32]string{
		0: "ITEM_UNSPECIFIED",
	}
	Item_Item_value = map[string]int32{
		"ITEM_UNSPECIFIED": 0,
	}
)

func (x Item_Item) Enum() *Item_Item {
	p := new(Item_Item)
	*p = x
	return p
}

func (x Item_Item) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item_Item) Descriptor() protoreflect.EnumDescriptor {
	return file_factorio_blueprints_v1_item_proto_enumTypes[0].Descriptor()
}

func (Item_Item) Type() protoreflect.EnumType {
	return &file_factorio_blueprints_v1_item_proto_enumTypes[0]
}

func (x Item_Item) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item_Item.Descriptor instead.
func (Item_Item) EnumDescriptor() ([]byte, []int) {
	return file_factorio_blueprints_v1_item_proto_rawDescGZIP(), []int{0, 0}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item Item_Item `protobuf:"varint,1,opt,name=item,proto3,enum=factorio_blueprints.v1.Item_Item" json:"item,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factorio_blueprints_v1_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_factorio_blueprints_v1_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_factorio_blueprints_v1_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetItem() Item_Item {
	if x != nil {
		return x.Item
	}
	return Item_ITEM_UNSPECIFIED
}

var File_factorio_blueprints_v1_item_proto protoreflect.FileDescriptor

var file_factorio_blueprints_v1_item_proto_rawDesc = []byte{
	0x0a, 0x21, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x65, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x5f, 0x62, 0x6c,
	0x75, 0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x5b, 0x0a, 0x04, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x35, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x21, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x5f, 0x62, 0x6c, 0x75,
	0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x1c, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x42, 0x42, 0x5a, 0x40, 0x6c, 0x6f, 0x65, 0x2e,
	0x79, 0x74, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x2d, 0x62, 0x6c, 0x75, 0x65,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x62, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x6f, 0x5f, 0x62, 0x6c, 0x75, 0x65,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_factorio_blueprints_v1_item_proto_rawDescOnce sync.Once
	file_factorio_blueprints_v1_item_proto_rawDescData = file_factorio_blueprints_v1_item_proto_rawDesc
)

func file_factorio_blueprints_v1_item_proto_rawDescGZIP() []byte {
	file_factorio_blueprints_v1_item_proto_rawDescOnce.Do(func() {
		file_factorio_blueprints_v1_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_factorio_blueprints_v1_item_proto_rawDescData)
	})
	return file_factorio_blueprints_v1_item_proto_rawDescData
}

var file_factorio_blueprints_v1_item_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_factorio_blueprints_v1_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_factorio_blueprints_v1_item_proto_goTypes = []interface{}{
	(Item_Item)(0), // 0: factorio_blueprints.v1.Item.Item
	(*Item)(nil),   // 1: factorio_blueprints.v1.Item
}
var file_factorio_blueprints_v1_item_proto_depIdxs = []int32{
	0, // 0: factorio_blueprints.v1.Item.item:type_name -> factorio_blueprints.v1.Item.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_factorio_blueprints_v1_item_proto_init() }
func file_factorio_blueprints_v1_item_proto_init() {
	if File_factorio_blueprints_v1_item_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_factorio_blueprints_v1_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_factorio_blueprints_v1_item_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_factorio_blueprints_v1_item_proto_goTypes,
		DependencyIndexes: file_factorio_blueprints_v1_item_proto_depIdxs,
		EnumInfos:         file_factorio_blueprints_v1_item_proto_enumTypes,
		MessageInfos:      file_factorio_blueprints_v1_item_proto_msgTypes,
	}.Build()
	File_factorio_blueprints_v1_item_proto = out.File
	file_factorio_blueprints_v1_item_proto_rawDesc = nil
	file_factorio_blueprints_v1_item_proto_goTypes = nil
	file_factorio_blueprints_v1_item_proto_depIdxs = nil
}
